# fly.toml app configuration file generated for portfolio-api-vjcgaq on 2026-05-26T21:23:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-api-divine-leaf-7748'
primary_region = 'iad'
console_command = '/rails/bin/rails console'

[build]

[env]
  HTTP_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
